import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";

const GOOGLE_FONTS_URL =
  "https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100..900&family=Gowun+Dodum:wght@400&family=Noto+Serif+KR:wght@200;300;400;500;600;700;900&family=Nanum+Myeongjo:wght@400;700;800&family=Gowun+Batang:wght@400;700&family=Black+Han+Sans:wght@400&family=Do+Hyeon:wght@400&family=Jua:wght@400&family=Gugi:wght@400&family=Sunflower:wght@300;500;700&family=Nanum+Pen+Script:wght@400&family=Gaegu:wght@300;400;700&family=Dokdo:wght@400&family=East+Sea+Dokdo:wght@400&display=swap";

const FONT_CSS_URLS = [
  GOOGLE_FONTS_URL,
  "https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css",
];

const USER_AGENT =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/145.0.7632.6 Safari/537.36";
const FETCH_ATTEMPTS = 3;
const FETCH_TIMEOUT_MS = 30_000;
const FETCH_RETRY_BASE_DELAY_MS = 1_000;

function extensionForUrl(url) {
  const ext = path.extname(new URL(url).pathname).toLowerCase();
  return ext || ".woff2";
}

function slugifyFamily(family) {
  return family
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function fetchWithRetry(url) {
  let lastError;
  for (let attempt = 1; attempt <= FETCH_ATTEMPTS; attempt += 1) {
    try {
      return await fetch(url, {
        headers: { "user-agent": USER_AGENT },
        signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      });
    } catch (error) {
      lastError = error;
      if (attempt === FETCH_ATTEMPTS) break;
      const delayMs = FETCH_RETRY_BASE_DELAY_MS * 2 ** (attempt - 1);
      console.warn(`Fetch failed for ${url}; retrying in ${delayMs}ms (${attempt}/${FETCH_ATTEMPTS})`);
      await delay(delayMs);
    }
  }
  throw lastError;
}

async function fetchText(url) {
  const response = await fetchWithRetry(url);
  if (!response.ok) throw new Error(`Failed to fetch ${url}: ${response.status}`);
  return response.text();
}

async function fetchFontFile(url, cache, fontsDir) {
  const cached = cache.get(url);
  if (cached) return cached;

  const response = await fetchWithRetry(url);
  if (!response.ok) throw new Error(`Failed to fetch font ${url}: ${response.status}`);
  const data = Buffer.from(await response.arrayBuffer());
  const hash = crypto.createHash("sha1").update(url).digest("hex").slice(0, 16);
  const sha256 = crypto.createHash("sha256").update(data).digest("hex");
  const filename = `${hash}${extensionForUrl(url)}`;
  await fs.writeFile(path.join(fontsDir, filename), data);
  const result = {
    filename,
    sourceUrl: url,
    sha256,
    bytes: data.length,
    cssUrl: `/render-fonts/fonts/${filename}`,
  };
  cache.set(url, result);
  return result;
}

async function localizeFontUrls(css, baseUrl, cache, fontsDir) {
  const withoutLocalSources = css.replace(/\s*local\([^)]+\),?/g, "");
  const urlRegex = /url\(([^)]+)\)/g;
  let result = "";
  let lastIndex = 0;
  for (const match of withoutLocalSources.matchAll(urlRegex)) {
    result += withoutLocalSources.slice(lastIndex, match.index);
    const raw = match[1].trim().replace(/^["']|["']$/g, "");
    if (raw.startsWith("data:")) {
      result += match[0];
    } else {
      const absoluteUrl = new URL(raw, baseUrl).toString();
      const fontFile = await fetchFontFile(absoluteUrl, cache, fontsDir);
      result += `url("${fontFile.cssUrl}")`;
    }
    lastIndex = match.index + match[0].length;
  }
  result += withoutLocalSources.slice(lastIndex);
  return result;
}

async function writeFamilyCssFiles(css, outDir) {
  const familyDir = path.join(outDir, "family-css");
  await fs.rm(familyDir, { recursive: true, force: true });
  await fs.mkdir(familyDir, { recursive: true });

  const blocksByFamily = new Map();
  for (const match of css.matchAll(/@font-face\s*\{[^}]*\}/g)) {
    const block = match[0];
    const familyMatch = block.match(/font-family:\s*['"]?([^;'"]+)/);
    if (!familyMatch) continue;
    const family = familyMatch[1].trim();
    const blocks = blocksByFamily.get(family) || [];
    blocks.push(block);
    blocksByFamily.set(family, blocks);
  }

  for (const [family, blocks] of blocksByFamily) {
    const filename = `${slugifyFamily(family)}.css`;
    const content = [
      "/* Generated by scripts/build-font-css.mjs. Do not edit by hand. */",
      ...blocks,
      "",
    ].join("\n");
    await fs.writeFile(path.join(familyDir, filename), content);
  }
  return blocksByFamily.size;
}

function parseFontFaceManifest(css, cache) {
  const filesByFilename = new Map(
    Array.from(cache.values()).map((file) => [file.filename, file]),
  );
  const entries = [];
  for (const match of css.matchAll(/@font-face\s*\{[^}]*\}/g)) {
    const block = match[0];
    const family = block.match(/font-family:\s*['"]?([^;'"]+)/)?.[1]?.trim();
    const weight = block.match(/font-weight:\s*([^;]+)/)?.[1]?.trim();
    const style = block.match(/font-style:\s*([^;]+)/)?.[1]?.trim() || "normal";
    const unicodeRange = block.match(/unicode-range:\s*([^;]+)/)?.[1]?.trim() || null;
    if (!family || !weight) continue;
    for (const urlMatch of block.matchAll(/url\(["']?([^"')]+)["']?\)/g)) {
      const filename = urlMatch[1].split("/").pop();
      const file = filename ? filesByFilename.get(filename) : undefined;
      if (!file) continue;
      entries.push({
        family,
        weight,
        style,
        unicodeRange,
        filename: file.filename,
        sha256: file.sha256,
        bytes: file.bytes,
        sourceUrl: file.sourceUrl,
      });
    }
  }
  return {
    version: 1,
    policy: {
      localSources: false,
      fallbackRendering: false,
      updateEnv: "ALLOW_FONT_MANIFEST_UPDATE=1",
    },
    files: Array.from(filesByFilename.values())
      .map(({ filename, sourceUrl, sha256, bytes }) => ({ filename, sourceUrl, sha256, bytes }))
      .sort((a, b) => a.filename.localeCompare(b.filename)),
    faces: entries.sort((a, b) =>
      `${a.family}:${a.weight}:${a.style}:${a.filename}`.localeCompare(`${b.family}:${b.weight}:${b.style}:${b.filename}`),
    ),
  };
}

async function writePinnedManifest(manifestPath, manifest) {
  const next = `${JSON.stringify(manifest, null, 2)}\n`;
  try {
    const current = await fs.readFile(manifestPath, "utf8");
    if (current === next) return;
    if (process.env.ALLOW_FONT_MANIFEST_UPDATE !== "1") {
      throw new Error(
        `Font manifest drift detected at ${manifestPath}. Set ALLOW_FONT_MANIFEST_UPDATE=1 to intentionally update bundled font versions.`,
      );
    }
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  await fs.writeFile(manifestPath, next);
}

async function main() {
  const cache = new Map();
  const chunks = [];
  const outDir = path.resolve("public/render-fonts");
  const fontsDir = path.join(outDir, "fonts");
  await fs.rm(fontsDir, { recursive: true, force: true });
  await fs.mkdir(fontsDir, { recursive: true });
  for (const url of FONT_CSS_URLS) {
    const css = await fetchText(url);
    chunks.push(await localizeFontUrls(css, url, cache, fontsDir));
  }

  const css = chunks.join("\n\n");
  const outPath = path.join(outDir, "font-css.css");
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, `/* Generated by scripts/build-font-css.mjs. Do not edit by hand. */\n${css}\n`);
  await writePinnedManifest(
    path.join(outDir, "font-manifest.json"),
    parseFontFaceManifest(css, cache),
  );
  const familyCount = await writeFamilyCssFiles(css, outDir);
  console.log(`Generated ${outPath} with ${cache.size} local font files, ${familyCount} family CSS files (${Math.round(css.length / 1024)} KiB CSS).`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
